/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cashier;

import Mainlogin.login;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.ResultSetMetaData;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asela gayan
 */
public class store extends javax.swing.JFrame {

    /**
     * Creates new form store
     */
    Connection con = null ;
        PreparedStatement pst = null ;
    
    public store() {
        initComponents();
        table_update();//update table
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    public void table_update(){//create method update table
    
    int c;//get veriable
    
     try {
            Class.forName("com.mysql.jdbc.Driver");//called mysql connection
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/registation_db","root","");
            Statement stm = (Statement) con.createStatement();//createstatement
            String Sql = "SELECT * FROM  STOREM";//select storem table
            ResultSet rs = stm.executeQuery(Sql);
            
            ResultSetMetaData rss = (ResultSetMetaData) rs.getMetaData();
            c = rss.getColumnCount();
            
            
            DefaultTableModel df = ( DefaultTableModel )jTable1.getModel();
            df.setRowCount(0);
            while(rs.next())
            {
              Vector v2 = new Vector();
              for(int a =1 ;a<=c; a++)
              {//get veriable values
               v2.add(rs.getString("id"));
               v2.add(rs.getString("brand"));
               v2.add(rs.getString("name"));
               v2.add(rs.getString("catagory"));
               v2.add(rs.getString("price"));
                
                    
              }
            df.addRow(v2);
            }
           //set the empty text fields
            id_txt.setText("");
            nam_txt.setText("");
            pr_txt.setText("");
            sb.setSelectedItem("");
            ca_type.setSelectedItem("");
            con.close();
            
        } catch (Exception e) {
            System.out.println(e);
        }
    
    
    
    }
    
    
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        id_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        sb = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        nam_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ca_type = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        pr_txt = new javax.swing.JTextField();
        add_btn = new javax.swing.JButton();
        edit_btn = new javax.swing.JButton();
        dele_btn = new javax.swing.JButton();
        se_btn = new javax.swing.JButton();
        sec_type = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        menu_btn = new javax.swing.JButton();
        exi_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(19, 15, 69));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));

        jPanel3.setBackground(new java.awt.Color(19, 15, 69));

        jLabel3.setBackground(new java.awt.Color(19, 15, 69));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Phone id:");

        id_txt.setName("id_txt"); // NOI18N

        jLabel1.setBackground(new java.awt.Color(19, 15, 69));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Brand:");

        sb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT PHONE BRAND", "Samsung", "Apple", "Huvawe", "Nokia", "Sony", "Micromax", "HTC", "BalckBerry", "Asus", "Xiaomi", "Oppo", "Microsoft", "Etel", "Google Pixcel", "Realme", "Vivo", "TCL", "Infix" }));
        sb.setName("sb"); // NOI18N

        jLabel2.setBackground(new java.awt.Color(19, 15, 69));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Name:");

        nam_txt.setName("nam_txt"); // NOI18N

        jLabel5.setBackground(new java.awt.Color(19, 15, 69));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Catagory:");

        ca_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT ITEM TYPE", "Button Phone", "Samart Phone", "Tab", "I pad" }));
        ca_type.setName("ca_type"); // NOI18N

        jLabel4.setBackground(new java.awt.Color(19, 15, 69));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Price:");

        pr_txt.setName("pr_txt"); // NOI18N

        add_btn.setBackground(new java.awt.Color(19, 15, 69));
        add_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        add_btn.setForeground(new java.awt.Color(255, 0, 0));
        add_btn.setText("ADD");
        add_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51), 3));
        add_btn.setName("add_btn"); // NOI18N
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        edit_btn.setBackground(new java.awt.Color(19, 15, 69));
        edit_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        edit_btn.setForeground(new java.awt.Color(255, 0, 0));
        edit_btn.setText("EDIT");
        edit_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        edit_btn.setName("edit_btn"); // NOI18N
        edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btnActionPerformed(evt);
            }
        });

        dele_btn.setBackground(new java.awt.Color(19, 15, 69));
        dele_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dele_btn.setForeground(new java.awt.Color(255, 0, 51));
        dele_btn.setText("DELETE");
        dele_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        dele_btn.setName("dele_btn"); // NOI18N
        dele_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dele_btnActionPerformed(evt);
            }
        });

        se_btn.setBackground(new java.awt.Color(19, 15, 69));
        se_btn.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        se_btn.setForeground(new java.awt.Color(255, 0, 51));
        se_btn.setText("SEARCH");
        se_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        se_btn.setName("se_btn"); // NOI18N
        se_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                se_btnActionPerformed(evt);
            }
        });

        sec_type.setBackground(new java.awt.Color(19, 15, 69));
        sec_type.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sec_type.setForeground(new java.awt.Color(255, 0, 0));
        sec_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEARCH TYPE", "Search by Brand", "Search by Catagory" }));
        sec_type.setBorder(null);
        sec_type.setName("sec_type"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nam_txt))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ca_type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(id_txt)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(add_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(se_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pr_txt)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 27, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sec_type, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(edit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(dele_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nam_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ca_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pr_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_btn)
                    .addComponent(edit_btn)
                    .addComponent(dele_btn))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(se_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sec_type, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel6.setBackground(new java.awt.Color(19, 15, 69));
        jLabel6.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("       PHONE STORE DASHBOARD");

        jPanel4.setBackground(new java.awt.Color(19, 15, 69));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 0), 3));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "brand", "name", "catagory", "price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        menu_btn.setBackground(new java.awt.Color(19, 15, 69));
        menu_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menu_btn.setForeground(new java.awt.Color(255, 0, 0));
        menu_btn.setText("GO TO MIAN MENU");
        menu_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        menu_btn.setName("menu_btn"); // NOI18N
        menu_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_btnActionPerformed(evt);
            }
        });

        exi_btn.setBackground(new java.awt.Color(19, 15, 69));
        exi_btn.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        exi_btn.setForeground(new java.awt.Color(255, 0, 0));
        exi_btn.setText("EXIT");
        exi_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        exi_btn.setName("exi_btn"); // NOI18N
        exi_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exi_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(exi_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(menu_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(48, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(menu_btn)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exi_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        //set table model and get table data
        DefaultTableModel df = ( DefaultTableModel )jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
          //text field get values and set data jtable values
        id_txt.setText(df.getValueAt(selectedIndex, 0).toString());
        sb.setSelectedItem(df.getValueAt(selectedIndex, 1).toString());
        nam_txt.setText(df.getValueAt(selectedIndex, 2).toString());
        ca_type.setSelectedItem(df.getValueAt(selectedIndex, 3).toString());
        pr_txt.setText(df.getValueAt(selectedIndex, 4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void edit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btnActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel df = ( DefaultTableModel )jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        //update the storem table
        try {
            //get text field valeues
            int id = Integer.parseInt(df.getValueAt(selectedIndex,0).toString());
            String brand = sb.getSelectedItem().toString();
            String name =nam_txt .getText();
            String catagory = ca_type.getSelectedItem().toString();
            String price = pr_txt.getText();

            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/registation_db","root","");

            String sql = "UPDATE storem set brand =?,name =?,price=?,catagory =? where id=?  ";
            pst= (PreparedStatement) con.prepareCall(sql);
            //set tha data 
            pst.setString(1, brand);
            pst.setString(2,name);
            pst.setString(3, price);
            pst.setString(4, catagory);
            pst.setInt(5, id);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "UPDATE RECORD SUCESSFULY");
            table_update();

            id_txt.setText("");
            nam_txt.setText("");
            pr_txt.setText("");
            sb.setSelectedItem("");
            ca_type.setSelectedItem("");
            con.close();

        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_edit_btnActionPerformed

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        // TODO add your handling code here:

        String JdbcURL = "jdbc:mysql://localhost:3306/registation_db?" + "autoReconnect=true&useSSL=false";
        String Username = "root";
        String password = "";
        //Add the phones record in storem table

        String id = id_txt.getText();
        String brand = sb.getSelectedItem().toString();
        String name =nam_txt .getText();
        String catagory =ca_type.getSelectedItem().toString();
        String price = pr_txt.getText();

        int id1 = Integer.parseInt(id);
        
        if(id.trim().equals("") || brand.trim().equals("SELECT PHONE BRAND") || name.trim().equals("")
                || catagory.trim().equals("SELECT ITEM TYPE")|| price.trim().equals(""))
        {
           JOptionPane.showMessageDialog(this, "One Or More Fields Are Empty");
        }
        else{

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/registation_db","root","");
            Statement stm = (Statement) con.createStatement();
            String Sql = "INSERT INTO STOREM VALUES("+id1+",'"+brand+"','"+name+"','"+catagory+"',"+price+")";//use insert in save the tha values in storem table
            stm.executeUpdate(Sql);

            JOptionPane.showMessageDialog(this, "ADDED SUCESSFULY");
            table_update();

            id_txt.setText("");
            sb.setSelectedItem("");
            nam_txt.setText("");
            ca_type.setSelectedItem("");
            pr_txt.setText("");
            id_txt.requestFocus();
            con.close();

        } catch (Exception e) {
            System.out.println(e);
        }
        }
    }//GEN-LAST:event_add_btnActionPerformed

    private void dele_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dele_btnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel df = ( DefaultTableModel )jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        //create code delete the storem table records delete
        
         try {
            int id = Integer.parseInt(df.getValueAt(selectedIndex,0).toString());
            int dialogResult = JOptionPane.showConfirmDialog(null,"DO YOU WHANT DELETE RECORD","WARNING",JOptionPane.YES_NO_OPTION);
           if(dialogResult == JOptionPane.YES_OPTION)
             {
             
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/registation_db","root","");
             
            String sql  ="delete  from storem where id =? ";
            pst= (PreparedStatement) con.prepareCall(sql);
            
  
            pst.setInt(1, id);
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(rootPane, "RECORD DELETED !!!!");
             table_update();
        
            id_txt.setText("");
            sb.setSelectedItem("");
            nam_txt.setText("");
            ca_type.setSelectedItem("");
            pr_txt.setText("");
            id_txt.requestFocus();
            con.close();
             }
            
        } catch (Exception e) {
            System.out.println(e);
    }                             
        
    }//GEN-LAST:event_dele_btnActionPerformed

    private void menu_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_btnActionPerformed
        // TODO add your handling code here:
        //go to main menu
        login l =new login();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_menu_btnActionPerformed

    private void exi_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exi_btnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exi_btnActionPerformed

    private void se_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_se_btnActionPerformed
        // TODO add your handling code here:
        //if use the search name and brand and catagory
        String setype = sec_type.getSelectedItem().toString();
        if(setype.trim().equals("SEARCH TYPE")){
           JOptionPane.showMessageDialog(rootPane, "INVALID INPUT !!!!");
        }
        else if (setype.trim().equals("Search by Brand")){
          sebybrand sb = new  sebybrand();
          sb.setVisible(true);
          dispose(); 
        }
        else if (setype.trim().equals("Search by Catagory")){
            sebybrand sb = new  sebybrand();
          sb.setVisible(true);
          dispose();
        }
    }//GEN-LAST:event_se_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new store().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JComboBox<String> ca_type;
    private javax.swing.JButton dele_btn;
    private javax.swing.JButton edit_btn;
    private javax.swing.JButton exi_btn;
    private javax.swing.JTextField id_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton menu_btn;
    private javax.swing.JTextField nam_txt;
    private javax.swing.JTextField pr_txt;
    private javax.swing.JComboBox<String> sb;
    private javax.swing.JButton se_btn;
    private javax.swing.JComboBox<String> sec_type;
    // End of variables declaration//GEN-END:variables
}
